steps:
- name: 'gcr.io/cloud-builders/docker:latest'
  args: ['build','-f', 'trainer.dockerfile', '-t', 'gcr.io/dtumlops-374716/exercises', '.']
- name: 'gcr.io/cloud-builders/docker:latest'
  args: ['push', 'gcr.io/dtumlops-374716/exercises']